Add login/register component
RedRad1sh/media-tracker-vue pull request #35
Opened 2024-01-04 16:08 UTC by Th3Ro

2024-01-04 22:32 UTC, RedRad1sh requested changes

2024-01-04 22:32 UTC, RedRad1sh commented on src/components/LoginPage.vue
> +              </label>
в исходниках видимо забыл поле для ссылки на аватар добавить, нужно тоже тут где-то сделать

2024-01-04 22:32 UTC, RedRad1sh commented on package.json
>  }
я так понимаю Леху больше сил ждать нет

2024-01-05 10:06 UTC, Th3Ro commented on package.json
>  }
Да

2024-01-05 14:53 UTC, RedRad1sh approved these changes

2024-01-05 16:09 UTC, merged